from pathlib import Path


# Directories for data which comes with mescal
DATA_DIR = Path(__file__).resolve().parent / "data"

# Directories for data which is generated by mescal
DIR_DATABASE_CACHE = Path(__file__).resolve().parent / "export" / "cache"
