from pathlib import Path


# Directories for data which comes with mescal
DATA_DIR = Path(__file__).resolve().parent / "data"

# Directories for data which is generated by mescal
DIR_DATABASE_CACHE = Path.cwd() / "export" / "cache"

# Main brightway project name (used for tests)
BW_PROJECT_NAME = "ecoinvent3.9.1A"
